---
name: Move new issues into the Inbox column

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.2.2
        with:
          project: IaC
          column: Inbox
          repo-token: ${{ secrets.GHACTIONTOKEN }}
